apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q1
  name: q1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - perl -Mbignum=bpi -wle "print bpi(2000)"
    image: perl
    name: q1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
