apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-cpu
  name: test-cpu
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchExpressions:
            - key: type
              operator: In
              values:
              - cpu
  containers:
  - image: nginx
    name: test-cpu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
